/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import src.ReservaDAO;
import src.ClienteDAO;
import src.EntrenadorDAO;
import src.Reserva;
import src.Cliente;
import src.Entrenador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
/**
 *
 * @author Dell
 */
public class FrmVerReservas extends javax.swing.JFrame {
    private ReservaDAO reservaDAO;
    private DefaultTableModel modeloTabla;
    private ClienteDAO clienteDAO;
    private EntrenadorDAO entrenadorDAO;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmVerReservas.class.getName());

    /**
     * Creates new form FrmVerReservas
     */
    public FrmVerReservas() {
        initComponents();
        reservaDAO=new ReservaDAO();
        clienteDAO=new ClienteDAO();
        entrenadorDAO=new EntrenadorDAO();
        configurarTabla();
        cargarReservas();
    }
    
    private void configurarTabla() {
         modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Hacer que la tabla sea de solo lectura
            }
        };
        // Configurar el modelo de la tabla
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Cliente");
        modeloTabla.addColumn("Entrenador");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Horario");
        modeloTabla.addColumn("Comentario");
        
        tblReservas.setModel(modeloTabla);
    }
    
    private void cargarReservas() {
        modeloTabla.setRowCount(0); // Limpiar tabla
        
        List<Reserva> reservas = reservaDAO.listarReservas();
        
        for (Reserva reserva : reservas) {
            // Obtener nombres de cliente y entrenador
            String nombreCliente = obtenerNombreCliente(reserva.getIdCliente());
            String nombreEntrenador = obtenerNombreEntrenador(reserva.getIdEntrenador());
            String horario = reserva.getHoraInicio() + " - " + reserva.getHoraFin();
            String fechaFormateada = formatearFecha(reserva.getFecha());
            
            modeloTabla.addRow(new Object[]{
                "R" + String.format("%03d", reserva.getIdReserva()),
                nombreCliente,
                nombreEntrenador,
                fechaFormateada,
                horario,
                reserva.getComentario()
            });
        }
    }
    private String obtenerNombreCliente(int idCliente) {
        for (Cliente cliente : clienteDAO.obtenerClientes()) {
            if (cliente.getId() == idCliente) {
                return cliente.getNombre();
            }
        }
        return "Cliente no encontrado";
    }
     private String obtenerNombreEntrenador(int idEntrenador) {
        for (Entrenador entrenador : entrenadorDAO.listarEntrenadores()) {
            if (entrenador.getId() == idEntrenador) {
                return entrenador.getNombre();
            }
        }
        return "Entrenador no encontrado";
    }
    private String formatearFecha(String fechaMySQL) {
        // Convierte "2024-12-15" a "15/12/2024"
        if (fechaMySQL.contains("-")) {
            String[] partes = fechaMySQL.split("-");
            if (partes.length == 3) {
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        }
        return fechaMySQL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollBar();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista de Reservas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Reservas - SmartGym");

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblReservas);

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Buscar:");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String textoBusqueda = txtBuscar.getText().trim().toLowerCase();
        
        if (textoBusqueda.isEmpty()) {
            cargarReservas();
            return;
        }
        
        modeloTabla.setRowCount(0); // Limpiar tabla
        List<Reserva> reservas = reservaDAO.listarReservas();
        
        for (Reserva reserva : reservas) {
            String nombreCliente = obtenerNombreCliente(reserva.getIdCliente());
            String nombreEntrenador = obtenerNombreEntrenador(reserva.getIdEntrenador());
            String horario = reserva.getHoraInicio() + " - " + reserva.getHoraFin();
            String fechaFormateada = formatearFecha(reserva.getFecha());
            
            // Buscar en cliente, entrenador o comentario
            if (nombreCliente.toLowerCase().contains(textoBusqueda) ||
                nombreEntrenador.toLowerCase().contains(textoBusqueda) ||
                reserva.getComentario().toLowerCase().contains(textoBusqueda)) {
                
                modeloTabla.addRow(new Object[]{
                    "R" + String.format("%03d", reserva.getIdReserva()),
                    nombreCliente,
                    nombreEntrenador,
                    fechaFormateada,
                    horario,
                    reserva.getComentario()
                });
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tblReservas.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una reserva para eliminar");
            return;
        }
        
        // Obtener ID de la reserva seleccionada
        String idReservaStr = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        int idReserva = Integer.parseInt(idReservaStr.substring(1)); // Quitar la "R"
        
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar la reserva " + idReservaStr + "?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            if (reservaDAO.eliminarReserva(idReserva)) {
                JOptionPane.showMessageDialog(this, "Reserva eliminada exitosamente");
                cargarReservas(); // Recargar tabla
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar la reserva");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
        "¿Está seguro de que desea salir?",
        "Confirmar Salida",
        JOptionPane.YES_NO_OPTION);
    
    if (respuesta == JOptionPane.YES_OPTION) {
        this.dispose();
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmVerReservas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollBar scrollPane;
    private javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
