/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import src.ReservaDAO;
import src.ClienteDAO;
import src.EntrenadorDAO;
import src.Cliente;
import src.Entrenador;
import src.Reserva;
import javax.swing.JOptionPane;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author Dell
 */
public class FrmAgendarReserva extends javax.swing.JFrame {
    private ReservaDAO reservaDAO;
    private ClienteDAO clienteDAO;
    private EntrenadorDAO entrenadorDAO;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAgendarReserva.class.getName());

    /**
     * Creates new form FrmAgendarReserva
     */
    public FrmAgendarReserva() {
        initComponents();
        reservaDAO=new ReservaDAO();
        clienteDAO=new ClienteDAO();
        entrenadorDAO= new EntrenadorDAO();
        
        cargarClientes();
        cargarEntrenadores();
        cargarHorarios();
        
    }
    private void cargarClientes(){
        comboClientes.removeAllItems();
        // Agregar opción por defecto
        comboClientes.addItem("-- Seleccione Cliente --");
        
        for (Cliente cliente : clienteDAO.obtenerClientes()) {
            // Mostrar ID formateado + nombre en el combo
            comboClientes.addItem(cliente.getIdFormateado() + " - " + cliente.getNombre());
        }
    }
    private void cargarEntrenadores(){
         comboEntrenadores.removeAllItems();
        // Agregar opción por defecto
        comboEntrenadores.addItem("-- Seleccione Entrenador --");
        
        for (Entrenador entrenador : entrenadorDAO.listarEntrenadores()) {
            // Mostrar ID formateado + nombre + especialidad
            comboEntrenadores.addItem(entrenador.getIdFormateado() + " - " + 
                                    entrenador.getNombre() + " (" + entrenador.getEspecialidad() + ")");
        }
    }
    private void cargarHorarios(){
        comboHorarios.removeAllItems();
        // Agregar los 4 horarios fijos
        comboHorarios.addItem("-- Seleccione Horario --");
        comboHorarios.addItem("1. Mañana: 08:00 - 10:00");
        comboHorarios.addItem("2. Mañana: 10:00 - 12:00");
        comboHorarios.addItem("3. Tarde: 14:00 - 16:00");
        comboHorarios.addItem("4. Tarde: 16:00 - 18:00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboClientes = new javax.swing.JComboBox<>();
        comboEntrenadores = new javax.swing.JComboBox<>();
        comboHorarios = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextPane();
        txtFecha = new javax.swing.JTextField();
        btnAgendar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reservas");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Agendar Reserva - SmartGym");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Cliente:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("Entrenador:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("Horario:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("Comentario:");

        comboClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboEntrenadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboHorarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jScrollPane1.setViewportView(txtComentario);

        btnAgendar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnAgendar.setText("Agendar");
        btnAgendar.addActionListener(this::btnAgendarActionPerformed);

        btnCancelar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalir.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboClientes, 0, 215, Short.MAX_VALUE)
                                            .addComponent(comboEntrenadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboHorarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtFecha)))
                                    .addComponent(jLabel6))
                                .addGap(63, 63, 63))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 114, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboEntrenadores, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        // Validar selección de cliente
        if (comboClientes.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente");
            return;
        }
        
        // Validar selección de entrenador
        if (comboEntrenadores.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un entrenador");
            return;
        }
        
        // Validar fecha
        String fecha = txtFecha.getText().trim();
    if (fecha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese la fecha");
        return;
    }
        
        // Validar formato de fecha (dd/mm/aaaa)
        if (!fecha.matches("\\d{2}/\\d{2}/\\d{4}")) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use dd/mm/aaaa");
        return;
    }
        // CONVERTIR formato dd/mm/aaaa a aaaa-mm-dd para MySQL
    String fechaMySQL = convertirFechaAMySQL(fecha);
        
        // Validar horario
        if (comboHorarios.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un horario");
            return;
        }
        
        // Obtener IDs de cliente y entrenador
        int idCliente = obtenerIdDeCombo(comboClientes.getSelectedItem().toString());
        int idEntrenador = obtenerIdDeCombo(comboEntrenadores.getSelectedItem().toString());
        
        // Obtener horarios
        String horarioSeleccionado = comboHorarios.getSelectedItem().toString();
        String horaInicio = obtenerHoraInicio(horarioSeleccionado);
        String horaFin = obtenerHoraFin(horarioSeleccionado);
        
        String comentario = txtComentario.getText().trim();
        
        // Crear y guardar reserva
        Reserva reserva = new Reserva(idCliente, idEntrenador, fechaMySQL, horaInicio, horaFin, comentario);
        
        if (reservaDAO.registrarReserva(reserva)) {
            JOptionPane.showMessageDialog(this, "Reserva agendada exitosamente");
            limpiarCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agendar la reserva");
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    private int obtenerIdDeCombo(String itemCombo) {
        // Extraer el ID numérico del texto del combo (ej: "C001 - Juan" → 1)
        if (itemCombo.contains(" - ")) {
            String idFormateado = itemCombo.split(" - ")[0];
            // Remover letra y obtener número: "C001" → 1
            return Integer.parseInt(idFormateado.substring(1));
        }
        return -1;
    }

    private String obtenerHoraInicio(String horario) {
        switch (horario) {
            case "1. Mañana: 08:00 - 10:00": return "08:00";
            case "2. Mañana: 10:00 - 12:00": return "10:00";
            case "3. Tarde: 14:00 - 16:00": return "14:00";
            case "4. Tarde: 16:00 - 18:00": return "16:00";
            default: return "";
        }
    }
    private String convertirFechaAMySQL(String fechaDDMMAAAA) {
    // Convierte "dd/mm/aaaa" a "aaaa-mm-dd"
    String[] partes = fechaDDMMAAAA.split("/");
    if (partes.length == 3) {
        return partes[2] + "-" + partes[1] + "-" + partes[0];
    }
    return fechaDDMMAAAA; // Si no puede convertir, devuelve la original
}

    private String obtenerHoraFin(String horario) {
        switch (horario) {
            case "1. Mañana: 08:00 - 10:00": return "10:00";
            case "2. Mañana: 10:00 - 12:00": return "12:00";
            case "3. Tarde: 14:00 - 16:00": return "16:00";
            case "4. Tarde: 16:00 - 18:00": return "18:00";
            default: return "";
        }
    }

    private void limpiarCampos() {
        comboClientes.setSelectedIndex(0);
        comboEntrenadores.setSelectedIndex(0);
        txtFecha.setText("");
        comboHorarios.setSelectedIndex(0);
        txtComentario.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAgendarReserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboClientes;
    private javax.swing.JComboBox<String> comboEntrenadores;
    private javax.swing.JComboBox<String> comboHorarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtComentario;
    private javax.swing.JTextField txtFecha;
    // End of variables declaration//GEN-END:variables
}
