/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import src.ReservaDAO;
import src.EntrenadorDAO;
import src.Entrenador;
import src.Reserva;
import src.ClienteDAO;
import src.Cliente;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author Dell
 */
public class FrmDisponibilidad extends javax.swing.JFrame {
    private ReservaDAO reservaDAO;
    private EntrenadorDAO entrenadorDAO;
    private ClienteDAO clienteDAO;
    
    // Los 4 horarios fijos del sistema
    private final String[] HORARIOS = {
        "08:00-10:00",
        "10:00-12:00", 
        "14:00-16:00",
        "16:00-18:00"
    };
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmDisponibilidad.class.getName());

    /**
     * Creates new form FrmDisponibilidad
     */
    public FrmDisponibilidad() {
        initComponents();
        reservaDAO=new ReservaDAO();
        entrenadorDAO=new EntrenadorDAO();
        clienteDAO=new ClienteDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoEntrenador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Disponibilidad Entrenadores");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Disponibilidad de Entrenadores - SmartGym");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel2.setText("Código Entrenador:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        jScrollPane1.setViewportView(txtResultados);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoEntrenador)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigoEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigoEntrenador = txtCodigoEntrenador.getText().trim();
        
        if (codigoEntrenador.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el código del entrenador");
            return;
        }
        
        // === DEPURACIÓN TEMPORAL ===
    System.out.println("=== INICIO DEPURACIÓN ===");
    System.out.println("Código ingresado: " + codigoEntrenador);
    
    // Obtener ID numérico del entrenador
    int idEntrenador = obtenerIdDeCodigo(codigoEntrenador);
    System.out.println("ID entrenador convertido: " + idEntrenador);
    
    if (idEntrenador == -1) {
        JOptionPane.showMessageDialog(this, "Código de entrenador inválido");
        return;
    }
        
        // Buscar entrenador
    Entrenador entrenador = buscarEntrenadorPorId(idEntrenador);
    if (entrenador == null) {
        JOptionPane.showMessageDialog(this, "Entrenador no encontrado");
        System.out.println("Entrenador NO encontrado con ID: " + idEntrenador);
        return;
    }
    System.out.println("Entrenador encontrado: " + entrenador.getNombre());
    
    // Obtener TODAS las reservas del entrenador (sin fecha específica)
    List<Reserva> todasLasReservas = reservaDAO.listarPorEntrenador(idEntrenador);
    
    System.out.println("Número TOTAL de reservas encontradas: " + todasLasReservas.size());
    for (Reserva r : todasLasReservas) {
        System.out.println("Reserva ID: " + r.getIdReserva() + 
                          ", Fecha: " + r.getFecha() +
                          ", Hora: " + r.getHoraInicio() + " a " + r.getHoraFin() +
                          ", Cliente ID: " + r.getIdCliente());
    }
    System.out.println("=== FIN DEPURACIÓN ===");
    
     
    // Generar reporte COMPLETO del entrenador
    String reporte = generarReporteCompleto(entrenador, todasLasReservas);
    
    // Mostrar resultados
    txtResultados.setText(reporte);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
    private int obtenerIdDeCodigo(String codigo) {
        // Convierte "E001" a 1
        if (codigo.matches("[Ee]\\d+")) {
            return Integer.parseInt(codigo.substring(1));
        }
        return -1;
    }
    
    private String generarReporteCompleto(Entrenador entrenador, List<Reserva> todasLasReservas) {
    StringBuilder sb = new StringBuilder();
    
    // Información del entrenador
    sb.append("=== INFORMACIÓN DEL ENTRENADOR ===\n");
    sb.append("Código: ").append(entrenador.getIdFormateado()).append("\n");
    sb.append("Nombre: ").append(entrenador.getNombre()).append("\n");
    sb.append("Especialidad: ").append(entrenador.getEspecialidad()).append("\n");
    sb.append("Edad: ").append(entrenador.getEdad()).append("\n");
    sb.append("Correo: ").append(entrenador.getCorreo()).append("\n\n");
    
    // TODAS las reservas del entrenador
    sb.append("=== TODAS LAS RESERVAS ===\n");
    if (todasLasReservas.isEmpty()) {
        sb.append("No tiene reservas registradas\n");
    } else {
        for (Reserva r : todasLasReservas) {
            String nombreCliente = obtenerNombreCliente(r.getIdCliente());
            sb.append("📅 ").append(formatearFecha(r.getFecha()))
              .append(" | ⏰ ").append(r.getHoraInicio()).append("-").append(r.getHoraFin())
              .append(" | 👤 ").append(nombreCliente)
              .append(" | #").append(r.getIdReserva())
              .append(" | ").append(r.getComentario()).append("\n");
        }
    }
    
    // Resumen
    sb.append("\n=== RESUMEN ===\n");
    sb.append("Total de reservas: ").append(todasLasReservas.size()).append("\n");
    
    return sb.toString();
}

private String obtenerNombreCliente(int idCliente) {
    for (Cliente cliente : clienteDAO.obtenerClientes()) {
        if (cliente.getId() == idCliente) {
            return cliente.getNombre();
        }
    }
    return "Cliente " + idCliente;
}
    
    private Entrenador buscarEntrenadorPorId(int id) {
        for (Entrenador entrenador : entrenadorDAO.listarEntrenadores()) {
            if (entrenador.getId() == id) {
                return entrenador;
            }
        }
        return null;
    }
    
    private String obtenerFechaActual() {
        // Retorna fecha en formato YYYY-MM-DD (puedes mejorar con DatePicker)
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        return sdf.format(new java.util.Date());
    }
    
    private String generarReporteDisponibilidad(Entrenador entrenador, List<Reserva> reservas, String fecha) {
        StringBuilder sb = new StringBuilder();
        
        // Información del entrenador
        sb.append("=== INFORMACIÓN DEL ENTRENADOR ===\n");
        sb.append("Código: ").append(entrenador.getIdFormateado()).append("\n");
        sb.append("Nombre: ").append(entrenador.getNombre()).append("\n");
        sb.append("Especialidad: ").append(entrenador.getEspecialidad()).append("\n");
        sb.append("Fecha consultada: ").append(formatearFecha(fecha)).append("\n\n");
        
        sb.append("=== DISPONIBILIDAD ===\n");
        
        // Verificar cada horario
        for (String horario : HORARIOS) {
            String[] partes = horario.split("-");
            String horaInicio = partes[0];
            String horaFin = partes[1];
            
            boolean ocupado = false;
            String infoReserva = "";
            
            // Verificar si hay reserva en este horario
            for (Reserva reserva : reservas) {
                if (reserva.getHoraInicio().equals(horaInicio) && 
                    reserva.getHoraFin().equals(horaFin)) {
                    ocupado = true;
                    infoReserva = " - OCUPADO (Reserva #" + reserva.getIdReserva() + ")";
                    break;
                }
            }
            
            if (ocupado) {
                sb.append("❌ ").append(horario).append(infoReserva).append("\n");
            } else {
                sb.append("✅ ").append(horario).append(" - DISPONIBLE\n");
            }
        }
        
        // Estadísticas
        sb.append("\n=== RESUMEN ===\n");
        int totalHorarios = HORARIOS.length;
        int ocupados = reservas.size();
        int disponibles = totalHorarios - ocupados;
        
        sb.append("Horarios disponibles: ").append(disponibles).append("/").append(totalHorarios).append("\n");
        sb.append("Horarios ocupados: ").append(ocupados).append("/").append(totalHorarios).append("\n");
        
        return sb.toString();
    }
     private String formatearFecha(String fechaMySQL) {
        // Convierte "2024-12-15" a "15/12/2024"
        if (fechaMySQL.contains("-")) {
            String[] partes = fechaMySQL.split("-");
            if (partes.length == 3) {
                return partes[2] + "/" + partes[1] + "/" + partes[0];
            }
        }
        return fechaMySQL;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmDisponibilidad().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoEntrenador;
    private javax.swing.JTextArea txtResultados;
    // End of variables declaration//GEN-END:variables
}
