package views;
import javax.swing.JOptionPane;

public class FrmPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPrincipal.class.getName());

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRegistrarCliente = new javax.swing.JButton();
        btnRegistrarEntrenador = new javax.swing.JButton();
        btnAgendarReserva = new javax.swing.JButton();
        btnVerReservas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEntrenadores = new javax.swing.JButton();
        btnDisponibilidad = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Reservas - Menu Principal");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("SmartGym ");

        btnRegistrarCliente.setBackground(new java.awt.Color(204, 255, 204));
        btnRegistrarCliente.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(this::btnRegistrarClienteActionPerformed);

        btnRegistrarEntrenador.setBackground(new java.awt.Color(204, 255, 204));
        btnRegistrarEntrenador.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnRegistrarEntrenador.setText("Registrar Entrenadores");
        btnRegistrarEntrenador.addActionListener(this::btnRegistrarEntrenadorActionPerformed);

        btnAgendarReserva.setBackground(new java.awt.Color(204, 255, 204));
        btnAgendarReserva.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnAgendarReserva.setText("Agendar Reserva");
        btnAgendarReserva.addActionListener(this::btnAgendarReservaActionPerformed);

        btnVerReservas.setBackground(new java.awt.Color(204, 255, 204));
        btnVerReservas.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnVerReservas.setText("Ver Todas Las Reservas");
        btnVerReservas.addActionListener(this::btnVerReservasActionPerformed);

        btnClientes.setBackground(new java.awt.Color(204, 255, 204));
        btnClientes.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnClientes.setText("Relación de Clientes");
        btnClientes.addActionListener(this::btnClientesActionPerformed);

        btnEntrenadores.setBackground(new java.awt.Color(204, 255, 204));
        btnEntrenadores.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnEntrenadores.setText("Relación de Entrenadores");
        btnEntrenadores.addActionListener(this::btnEntrenadoresActionPerformed);

        btnDisponibilidad.setBackground(new java.awt.Color(204, 255, 204));
        btnDisponibilidad.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnDisponibilidad.setText("Ver Disponibilidad de Entrenadores");
        btnDisponibilidad.addActionListener(this::btnDisponibilidadActionPerformed);

        btnSalir.setBackground(new java.awt.Color(102, 255, 204));
        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 102, 102));
        btnSalir.setText("Salir del Sistema");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnRegistrarEntrenador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgendarReserva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerReservas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisponibilidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEntrenadores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarCliente)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrarEntrenador)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarReserva)
                .addGap(18, 18, 18)
                .addComponent(btnVerReservas)
                .addGap(28, 28, 28)
                .addComponent(btnClientes)
                .addGap(27, 27, 27)
                .addComponent(btnEntrenadores)
                .addGap(18, 18, 18)
                .addComponent(btnDisponibilidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
       FrmRegistrarCliente frm = new FrmRegistrarCliente();
       frm.setVisible(true);
        
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnRegistrarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEntrenadorActionPerformed
       FrmRegistrarEntrenador frm=new FrmRegistrarEntrenador();
       frm.setVisible(true);

    }//GEN-LAST:event_btnRegistrarEntrenadorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
        "Gracias por su visita...SmartGym",
        "Confirmar Salida",
        JOptionPane.YES_NO_OPTION);
    
    if (respuesta == JOptionPane.YES_OPTION) {
        this.dispose();
    }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgendarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarReservaActionPerformed
        FrmAgendarReserva frm=new FrmAgendarReserva();
        frm.setVisible(true);
    }//GEN-LAST:event_btnAgendarReservaActionPerformed

    private void btnVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservasActionPerformed
        FrmVerReservas frm=new FrmVerReservas();
        frm.setVisible(true);
    }//GEN-LAST:event_btnVerReservasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        FrmClientes frm=new FrmClientes();
        frm.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEntrenadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrenadoresActionPerformed
        FrmEntrenadores frm=new FrmEntrenadores();
        frm.setVisible(true);
    }//GEN-LAST:event_btnEntrenadoresActionPerformed

    private void btnDisponibilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisponibilidadActionPerformed
        FrmDisponibilidad frm=new FrmDisponibilidad();
        frm.setVisible(true); 
    }//GEN-LAST:event_btnDisponibilidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarReserva;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnDisponibilidad;
    private javax.swing.JButton btnEntrenadores;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarEntrenador;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerReservas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
